# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for update
        id: history
        run: echo "::set-output name=value::$(git whatchanged --since="1 day ago" Docs)"

      - name: Install BasicTex
        if: steps.history.outputs.value != ''
        run: |
          brew install --cask basictex
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          sudo tlmgr install datetime fmtcount latexdiff titlesec zref

      - name: Build Docs
        if: steps.history.outputs.value != ''
        run: |
          eval "$(/usr/libexec/path_helper)"
          Docs/BuildDocs.tool

      - name: Upload Docs
        if: steps.history.outputs.value != ''
        uses: actions/upload-artifact@v2
        with:
          name: Docs
          path: Docs
